### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by noob211** [ecmnet/MAVSlam#6]
.

**Comment by ecmnet** [comment]
Please check the Firmware version of the camera. It needs to be provided when creating the driver context.

**Comment by alireza2033** [comment]
hi thank for your support 
i have two questions 
one of them is that i compiled librealsense 1.12 
and i can run demo.cpp and its work 
but did you mean the version of the librarie or the firmware of camera and how can i check this and how can i fix this can you please explain more?

and the question number 2 is 
can i run this code on upcore ? 
i get the io error for yellow and blue and red led 
i mean up.led and others
so can i run this on ubuntu!? 
because i couldn't run ubilinux on upcore
